/**
 * @module mod/boxAnimatePop 箱子作业展示动画
 */
define(function(require) {
    'use strict'
    var jsrender = require('plugin/jsrender/jsrender');

    var centerboxAnimateTemplate = '<div class="popup popup-left fixed-center md inline bay-pop j-box-animate">'
            + '<div class="pop-content ">'
                + '<div class="pop-header">'
                   + '<p class="pop-title">集装箱编号{{>CTN_NO}}</p>'
                   + '<span class="pop-close j-close">关闭</span>'
                + '</div>'
                + '<div class="pop-body">'
                    // + '<img src="../../src/js/mod/popup/images/road.png" alt="" />'
                + '{{if CURRENT_STATUS == "ONROAD"}}'
                     + '<div class="{{>CURRENT_STATUS}} jobAnimate">'
                         + '<div class="base"></div>'
                         + '<div class="tree"></div>'
                         + '<div class="car"></div>'
                     + '</div>'
                     + '<div class="jobInfo">'
                         + '<ul>'
                             + '<li>'
                                 + '<span class="pull-left">道路：</span>'
                                 + '<span class="pull-right"></span>'
                             + '</li>'
                             + '<li>'
                                 + '<span class="pull-left">集卡编号：</span>'
                                 + '<span class="pull-right">{{>TRUCK_CODE}}</span>'
                             + '</li>'
                             + '<li>'
                                 + '<span class="pull-left">集装箱编号：</span>'
                                 + '<span class="pull-right">{{>CTN_NO}}</span>'
                             + '</li>'
                             + '<li>'
                                 + '<span class="pull-left">集装箱箱主：</span>'
                                 + '<span class="pull-right">{{>CTN_OPERATOR_CODE}}</span>'
                             + '</li>'
                             + '<li>'
                                 + '<span class="pull-left">作业类型：</span>'
                                 + '<span class="pull-right">'
                                    + '{{if JOB_TYPE == "LOAD"}}'
                                         + '装船'
                                    + '{{else JOB_TYPE == "DSCH"}}'
                                         + '卸船'
                                    + '{{else JOB_TYPE == "RECV"}}'
                                         + '进箱'
                                    + '{{else JOB_TYPE == "DLVR"}}'
                                         + '提箱'
                                    + '{{/if}}'
                                 + '</span>'
                             + '</li>'
                         + '</ul>'
                     + '</div>'
                 + '{{else CURRENT_STATUS == "INYARD" || CURRENT_STATUS == "OUTYARD"}}'
                      + '<div class="{{>CURRENT_STATUS}} jobAnimate">'
                          + '<div class="base"></div>'
                          + '<div class="gantrycrane"></div>'
                          + '<div class="grabUp"></div>'
                          + '<div class="grabDown"></div>'
                          + '<div class="guardrail"></div>'
                          + '<div class="car"></div>'
                      + '</div>'
                      + '<div class="jobInfo">'
                          + '<ul>'
                              + '<li>'
                                  + '<span class="pull-left">堆场编号：</span>'
                                  + '<span class="pull-right">{{>ACTUAL_POSITION_BLOCK}}</span>'
                              + '</li>'
                              + '<li>'
                                  + '<span class="pull-left">龙门吊编号：</span>'
                                  + '<span class="pull-right">{{>EQUIPMENT_CODE}}</span>'
                              + '</li>'
                              + '<li>'
                                  + '<span class="pull-left">集卡编号：</span>'
                                  + '<span class="pull-right">{{>TRUCK_CODE}}</span>'
                              + '</li>'
                              + '<li>'
                                  + '<span class="pull-left">集装箱编号：</span>'
                                  + '<span class="pull-right">{{>CTN_NO}}</span>'
                              + '</li>'
                              + '<li>'
                                  + '<span class="pull-left">集装箱箱主：</span>'
                                  + '<span class="pull-right">{{>CTN_OPERATOR_CODE}}</span>'
                              + '</li>'
                              + '<li>'
                                  + '<span class="pull-left">作业类型：</span>'
                                  + '<span class="pull-right">'
                                     + '{{if JOB_TYPE == "LOAD"}}'
                                          + '装船'
                                     + '{{else JOB_TYPE == "DSCH"}}'
                                          + '卸船'
                                     + '{{else JOB_TYPE == "RECV"}}'
                                          + '进箱'
                                     + '{{else JOB_TYPE == "DLVR"}}'
                                          + '提箱'
                                     + '{{/if}}'
                                  + '</span>'
                              + '</li>'
                          + '</ul>'
                      + '</div>'
                + '{{else CURRENT_STATUS == "OUTSHIP" || CURRENT_STATUS == "INSHIP"}}'
                    + '<div class="{{>CURRENT_STATUS}} jobAnimate">'
                        + '<div class="base"></div>'
                        + '<div class="gantrycrane"></div>'
                        + '<div class="gantryString"></div>'
                        + '<div class="gantryDown"></div>'
                        + '<div class="gantryDown"></div>'
                        + '<div class="gantryUp"></div>'
                        + '<div class="gantryShadow"></div>'
                        + '<div class="grabUp"></div>'
                        + '<div class="grabDownY"></div>'
                        + '<div class="grabDownN"></div>'
                        + '<div class="tree"></div>'
                        + '<div class="car"></div>'
                    + '</div>'
                    + '<div class="jobInfo">'
                        + '<ul>'
                            + '<li>'
                                + '<span class="pull-left">泊位编号：</span>'
                                + '<span class="pull-right">{{>ACTUAL_LOCATION}}</span>'
                            + '</li>'
                            + '<li>'
                                + '<span class="pull-left">桥吊编号：</span>'
                                + '<span class="pull-right">{{>EQUIPMENT_CODE}}</span>'
                            + '</li>'
                            + '<li>'
                                + '<span class="pull-left">船名航次：</span>'
                                + '<span class="pull-right">{{>VESSEL_REFERENCE}}</span>'
                            + '</li>'
                            + '<li>'
                                + '<span class="pull-left">集卡编号：</span>'
                                + '<span class="pull-right">{{>TRUCK_CODE}}</span>'
                            + '</li>'
                            + '<li>'
                                + '<span class="pull-left">集装箱编号：</span>'
                                + '<span class="pull-right">{{>CTN_NO}}</span>'
                            + '</li>'
                            + '<li>'
                                + '<span class="pull-left">集装箱箱主：</span>'
                                + '<span class="pull-right">{{>CTN_OPERATOR_CODE}}</span>'
                            + '</li>'
                            + '<li>'
                                + '<span class="pull-left">作业类型：</span>'
                                + '<span class="pull-right">'
                                   + '{{if JOB_TYPE == "LOAD"}}'
                                        + '装船'
                                   + '{{else JOB_TYPE == "DSCH"}}'
                                        + '卸船'
                                   + '{{else JOB_TYPE == "RECV"}}'
                                        + '进箱'
                                   + '{{else JOB_TYPE == "DLVR"}}'
                                        + '提箱'
                                   + '{{/if}}'
                                + '</span>'
                            + '</li>'
                        + '</ul>'
                    + '</div>'
                + '{{else CURRENT_STATUS == "OUTGATE" || CURRENT_STATUS == "INGATE"}}'
                     + '<div class="{{>CURRENT_STATUS}} jobAnimate">'
                         + '<div class="base"></div>'
                         + '<div class="car"></div>'
                     + '</div>'
                     + '<div class="jobInfo">'
                         + '<ul>'
                             + '<li>'
                                 + '<span class="pull-left">闸口编号：</span>'
                                 + '<span class="pull-right">'
                                    + '{{if JOB_TYPE == "LOAD"}}'
                                        + '闸口1'
                                    + '{{else}}'
                                        + '闸口2'
                                    + '{{/if}}'
                                 + '</span>'
                             + '</li>'
                             + '<li>'
                                 + '<span class="pull-left">目标堆场：</span>'
                                 + '<span class="pull-right">{{>ACTUAL_POSITION_BLOCK}}</span>'
                             + '</li>'
                             + '<li>'
                                 + '<span class="pull-left">集卡编号：</span>'
                                 + '<span class="pull-right">{{>TRUCK_CODE}}</span>'
                             + '</li>'
                             + '<li>'
                                 + '<span class="pull-left">集装箱编号：</span>'
                                 + '<span class="pull-right">{{>CTN_NO}}</span>'
                             + '</li>'
                             + '<li>'
                                 + '<span class="pull-left">集装箱箱主：</span>'
                                 + '<span class="pull-right">{{>CTN_OPERATOR_CODE}}</span>'
                             + '</li>'
                             + '<li>'
                                 + '<span class="pull-left">作业类型：</span>'
                                 + '<span class="pull-right">'
                                    + '{{if JOB_TYPE == "LOAD"}}'
                                         + '装船'
                                    + '{{else JOB_TYPE == "DSCH"}}'
                                         + '卸船'
                                    + '{{else JOB_TYPE == "RECV"}}'
                                         + '进箱'
                                    + '{{else JOB_TYPE == "DLVR"}}'
                                         + '提箱'
                                    + '{{/if}}'
                                 + '</span>'
                             + '</li>'
                         + '</ul>'
                     + '</div>'
                + '{{else}}'
                    + '<div class="OUTYARD jobAnimate">'
                          + '<div class="base"></div>'
                          + '<div class="gantrycrane"></div>'
                          + '<div class="grabUp"></div>'
                          + '<div class="grabDown"></div>'
                          + '<div class="guardrail"></div>'
                          + '<div class="car"></div>'
                      + '</div>'
                      + '<div class="jobInfo">'
                          + '<ul>'
                              + '<li>'
                                  + '<span class="pull-left">堆场编号：</span>'
                                  + '<span class="pull-right">{{>ACTUAL_POSITION_BLOCK}}</span>'
                              + '</li>'
                              + '<li>'
                                  + '<span class="pull-left">龙门吊编号：</span>'
                                  + '<span class="pull-right">{{>EQUIPMENT_CODE}}</span>'
                              + '</li>'
                              + '<li>'
                                  + '<span class="pull-left">集卡编号：</span>'
                                  + '<span class="pull-right">{{>TRUCK_CODE}}</span>'
                              + '</li>'
                              + '<li>'
                                  + '<span class="pull-left">集装箱编号：</span>'
                                  + '<span class="pull-right">{{>CTN_NO}}</span>'
                              + '</li>'
                              + '<li>'
                                  + '<span class="pull-left">集装箱箱主：</span>'
                                  + '<span class="pull-right">{{>CTN_OPERATOR_CODE}}</span>'
                              + '</li>'
                              + '<li>'
                                  + '<span class="pull-left">作业类型：</span>'
                                  + '<span class="pull-right">'
                                     + '{{if JOB_TYPE == "LOAD"}}'
                                          + '装船'
                                     + '{{else JOB_TYPE == "DSCH"}}'
                                          + '卸船'
                                     + '{{else JOB_TYPE == "RECV"}}'
                                          + '进箱'
                                     + '{{else JOB_TYPE == "DLVR"}}'
                                          + '提箱'
                                     + '{{/if}}'
                                  + '</span>'
                              + '</li>'
                          + '</ul>'
                      + '</div>'
                + '{{/if}}'
                + '</div>'
            + '</div>'
        + '</div>';
    var BOXANIMATEPOP = function (cfg) {
        if (!(this instanceof BOXANIMATEPOP)) {
            return new BOXANIMATEPOP().init(cfg);
        }
    };

    BOXANIMATEPOP.prototype = $.extend({}, {
        init: function (cfg) {
            this.observer = cfg.observer;
            this.elementId = cfg.elementId;
            this.wraper = $(this.elementId);
            this.bindEvent();
            return this;
        },
        bindEvent: function () {
            var that = this;
            this.wraper
                .on('click', '.j-box-animate .j-close', function () {
                    that.hide();
                });
        },
        /*
         *  绘制联合动画
         */
        renderBoxAnimationPop: function (data) {

            var wraperLeft = jsrender.templates(centerboxAnimateTemplate).render(data);
            if (!this.wraper.find('.popup-left').length) {
                this.wraper.append(wraperLeft);
            } else {
                this.wraper.find('.popup-left').html(wraperLeft).show();
            }
            this.wraper.find('.popup').removeClass('inline').show();
        },
        /**
         * 设置弹框位置
         */
        setPosition: function (position) {
            position === 'block' ? this.wraper.find('.popup').removeClass('inline').show() : this.wraper.find('.popup').addClass('inline').show();
        },
        /**
         * 隐藏弹框
         */
        hide: function () {
            this.wraper.find('.popup').removeClass('inline');
            this.wraper.find('.popup-left').hide();
        }
    });

    return BOXANIMATEPOP;
});